name: gokai_tools
description: Integration tool for managing, building, and creating Flutter applications with Gokai.
homepage: https://expidusos.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.0
  completion: ^1.0.1
  flutter_tools:
    path: vendor/flutter_tools
  intl: ^0.18.0
